# ##############################################################################
# OASIS: Open Algebra Software for Inferring Solutions
#
# build-npm-package.yml
# ##############################################################################

name: Build NPM Package

on:
    push:
        branches: [ "master" ]
    pull_request:
        branches: [ "master" ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    build_npm_package:
        runs-on: ubuntu-latest
        container: ghcr.io/open-algebra/emscripten:main

        steps:
            # Checks out the repository.
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set reusable strings
            id: strings
            shell: bash
            run: |
              echo "build-dir=$(pwd)/build" >> "$GITHUB_OUTPUT"

            # Configures CMake in a subdirectory.
          - name: Configure CMake
            run: >
                emcmake cmake
                -B ${{ steps.strings.outputs.build-dir }}
                -DOASIS_BUILD_JS=ON
                -DOASIS_BUILD_PARANOID=ON
                .

            # Builds Oasis with the given configuration.
          - name: Build Oasis
            run: >
                emmake cmake
                --build ${{ steps.strings.outputs.build-dir }}
                --target OasisJSWeb OasisJSNode

          - name: Test
            working-directory: ./bindings/js
            run: |
              cp ${{ steps.strings.outputs.build-dir }}/bindings/js/oasis-* .
              npm install
              npm test

          - name: Build NPM Package
            working-directory: ./bindings/js
            run: npm pack

            # Uploads the build, test, and code coverage artifacts.
          - name: Upload artifacts
            uses: actions/upload-artifact@v4
            with:
              name: npm-package-archive
              path: ./bindings/js/oasis-0.0.1.tgz
              overwrite: true
              compression-level: 0